### ISSUE TITLE
How to install this package?

### ISSUE THREAD

**Issue by MCFreddie777** [konradkalemba/blade-components-scoped-slots#1]
I downloaded your package using composer and tried to use it.

```
<x-ui.table
     :options="$options"
>
            @scopedslot('item', ($object))
                {{ $object }}
            @endscopedslot
</x-ui.table>
```

```
// ui/table.blade.php
   @forelse($options as $object)
        <tr>
            {{ $item($object) }}
        </tr>
    @empty
     <tr>
            nothing
     </tr>
    @endforelse
```

Ends up in:
__Array callback has to contain indices 0 and 1__

I registered your class in `app.php` in `providers`. Is there any other action I should do before using it?

**Comment by MCFreddie777** [comment]
Aaaaaaalllright. 

The problem was, that i already had $item defined in other @foreach, and it was an key-value array in the code of `table.blade.php` few lines above.

Changing `$item` to anything else like in `{{ $foo($object) }}` and also changing the same name in `  @scopedslot('foo', ($object))` did the work.

Also, an answer to my question about registering - You don't have to do it, laravel does it itself.

I leave this issue here - for people like me in the future.

**Comment by konradkalemba** [comment]
Great to hear that you have managed to make it work. As you wrote, I'll leave it for other folks that may come accross the same problem.
