### ISSUE TITLE
Using foreach or blade x component in scoped slots results to undefined variable: __env

### ISSUE THREAD

**Issue by MCFreddie777** [konradkalemba/blade-components-scoped-slots#2]
Using @foreach in scoped slot or using custom blade x component ends up in  __Undefined variable: \_\_env__ error
```
 @scopedslot('tableitem', ($item), ($options))
                <td>
                    <div class="flex items-center">
                        <x-user.circle
                            name="{{$item->login}}"
                        ></x-user.circle>
                        <span class="ml-3">{{ $item->login }}</span>
                    </div>
                </td>
@endscopedslot
```

**Comment by konradkalemba** [comment]
Hey @MCFreddie777, thanks for letting me know about the bug. It should be fixed now, can you check if it works now?

**Comment by MCFreddie777** [comment]
I just checked foreach - it works. What does not work is custom components in blade X - it breaks the properties in anonymous components.

**Comment by konradkalemba** [comment]
Try to use `@component` directive instead of the new syntax and let me know if it works, please.
