### ISSUE TITLE
Accessors do not work in scoped slots

### ISSUE THREAD

**Issue by MCFreddie777** [konradkalemba/blade-components-scoped-slots#3]
If you have in your model

```php
public function getFooAttribute() {
       return 'foo';
}
```

and you use it in scoped slot like this:
```php
@scopedslot('tableitem', ($item))
        @dump($item->foo);  {{-- works --}}
       {{ $item->foo }}  {{-- does not work --}}
@endscopedslot
```

**Comment by MCFreddie777** [comment]
Can be overriden by `$item['foo']` tho.
I'm not sure whether it's a bug or feature.

**Comment by konradkalemba** [comment]
Hey, sorry for late reply. 

I just tested custom attributes and they're working fine. Could you provide more info or the error if any you're getting?
